### ISSUE TITLE
orbit-db-io dependency is obsolete

### ISSUE THREAD

**Issue by gdethier** [orbitdb/orbit-db-access-controllers#62]
Current `orbit-db-io` dependency version is 0.3.0 while version 1.0.0 has been released on July 30 2021.

Version 0.3.0 of `orbit-db-io` is using a now deprecated interface of multiformats' CID (still calling `toBaseEncodedString` instead of `toString`). See below for an example of stacktrace I am getting currently when trying to create an OrbitDB instance.

```
at CID.get toBaseEncodedString [as toBaseEncodedString] (.../node_modules/multiformats/cjs/src/cid.js:94:11)
    at Object.writeCbor [as write] (.../node_modules/orbit-db-access-controllers/node_modules/orbit-db-io/index.js:70:19)
    at IPFSAccessController.save (.../node_modules/orbit-db-access-controllers/src/ipfs-access-controller.js:46:13)
    at Function.create (.../node_modules/orbit-db-access-controllers/src/access-controllers.js:68:20)
    ...
```

**Comment by spartanz51** [comment]
Same problem there.
